version: "3"
services:
  nginx:
    build: nginx
    ports:
      - "80:80"
    networks:
      - internal
    volumes:
      &shared_volume
      - ./.:/var/www/html/:ro
  php:
    build: .
    networks:
      - internal
    volumes: *shared_volume
  db:
    build: db
    environment:
      MYSQL_ROOT_PASSWORD: &MYSQL_ROOT_PASSWORD secret
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - internal
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: *MYSQL_ROOT_PASSWORD
    networks:
      - internal
networks:
  internal:
    driver: bridge
